version: '3.8'

services:

  furchain-text-mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  furchain-text-llama-cpp:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    restart: unless-stopped
    ports:
      - "8000:8080"
    volumes:
      - ./models:/models
    command: -m models/FusionNet_7Bx2_MoE_14B-Q4_K.gguf -c 1024 --host 0.0.0.0 --port 8080 --n-gpu-layers 99
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]