version: '3.8'

services:

  text-mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  text-llama-cpp:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    restart: unless-stopped
    ports:
      - "8000:8080"
    volumes:
      - "./data/llama-cpp:/models"
    command: -m models/nous-hermes-llama2-13b.Q4_K_M.gguf -c 4096 --host 0.0.0.0 --port 8080 --n-gpu-layers 99
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  audio-gpt-sovits:
    image: markyfsun/gpt-sovits:latest
    restart: unless-stopped
    ports:
      - "9880:9880"
    volumes:
      - "./data/gpt-sovits:/ref"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  audio-funasr:
    image: markyfsun/funasr-online-cpu:latest
    restart: unless-stopped
    ports:
      - "10095:10095"